# Usa una imagen oficial de Node.js como base
FROM node:18-alpine

# Establecer el directorio de trabajo en el contenedor
WORKDIR /home/miapp

# Copiar los archivos de package.json y nodemon.json al contenedor
COPY package*.json nodemon.json ./

# Instalar las dependencias de la aplicación
RUN npm install

# Instalar nodemon globalmente
RUN npm install -g nodemon

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 3000

# Comando por defecto para ejecutar la aplicación con nodemon
CMD ["npm", "dev"]
